# Generated by Django 3.1 on 2020-08-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eigo', '0002_auto_20200804_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
