# Generated by Django 3.1 on 2020-08-04 12:52

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('eigo', '0002_auto_20200804_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='memo',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AddField(
            model_name='phrase',
            name='memo',
            field=martor.models.MartorField(blank=True),
        ),
    ]
