# Generated by Django 3.1 on 2020-08-04 17:13

from django.db import migrations, models
import eigo.models


class Migration(migrations.Migration):

    dependencies = [
        ('eigo', '0003_auto_20200804_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snap',
            name='snap',
            field=models.ImageField(blank=True, upload_to=eigo.models.upload_image_to),
        ),
    ]
