# Generated by Django 3.1 on 2020-08-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eigo', '0004_auto_20200804_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phrase',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.RemoveField(
            model_name='example',
            name='user',
        ),
        migrations.RemoveField(
            model_name='snap',
            name='user',
        ),
    ]
